// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learningSidebar: [
    "start-here",
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
